### ISSUE TITLE
More examples on Rest API

### ISSUE THREAD

**Issue by ajayvers** [aleksey-stukalov/workshop#3]
The entire wiki is too good 👍 
Please update Rest API part with more examples.

**Comment by ajayvers** [comment]
for example - 
`http://localhost:8080/app/rest/v2/entities/workshop$Order?view=_local` to view .
 I want to know how to edit an order using rest ?

**Comment by jreznot** [comment]
It is just small introduction to the platform, please see full documentation for details: https://doc.cuba-platform.com/manual-6.5/rest_api_v2_usage_example.html
