### ISSUE TITLE
Screenshot on "Creating a new project" page does not get displayed

### ISSUE THREAD

**Issue by moritzreiter** [aleksey-stukalov/workshop#4]
On the "Creating a new project" page of the wiki, a screenshot does not get displayed because of an illegal white space between the label and the URI:

`![Create new project in Studio] (https://github.com/aleksey-stukalov/workshop/blob/master/screenshots/3_CREATING_A_NEW_PROJECT.png)`

**Comment by jreznot** [comment]
Hi, thank you!
We have fixed it
